//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("WorkOrderModel", "FK_Employee_Position", "Position", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WorkOrder.Position), "Employee", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WorkOrder.Employee))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("WorkOrderModel", "FK_WorkOrder_Employee", "Employee", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WorkOrder.Employee), "WorkOrder", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WorkOrder.WorkOrder))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("WorkOrderModel", "FK_WorkOrderProcLog_EventType", "EventType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WorkOrder.EventType), "WorkOrderProcLog", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WorkOrder.WorkOrderProcLog))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("WorkOrderModel", "FK_WorkOrder_OrderState", "OrderState", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WorkOrder.OrderState), "WorkOrder", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WorkOrder.WorkOrder))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("WorkOrderModel", "FK_WorkOrderDetail_WorkOrder", "WorkOrder", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WorkOrder.WorkOrder), "WorkOrderDetail", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WorkOrder.WorkOrderDetail))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("WorkOrderModel", "FK_WorkOrderProcLog_WorkOrder", "WorkOrder", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WorkOrder.WorkOrder), "WorkOrderProcLog", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WorkOrder.WorkOrderProcLog))]

// Original file name:
// Generation date: 19.12.2008 00:18:10
namespace WorkOrder
{
    
    /// <summary>
    /// There are no comments for WorkOrderEntities1 in the schema.
    /// </summary>
    public partial class WorkOrderEntities1 : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new WorkOrderEntities1 object using the connection string found in the 'WorkOrderEntities1' section of the application configuration file.
        /// </summary>
        public WorkOrderEntities1() : 
                base("name=WorkOrderEntities1", "WorkOrderEntities1")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new WorkOrderEntities1 object.
        /// </summary>
        public WorkOrderEntities1(string connectionString) : 
                base(connectionString, "WorkOrderEntities1")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new WorkOrderEntities1 object.
        /// </summary>
        public WorkOrderEntities1(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "WorkOrderEntities1")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Employee> Employee
        {
            get
            {
                if ((this._Employee == null))
                {
                    this._Employee = base.CreateQuery<Employee>("[Employee]");
                }
                return this._Employee;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Employee> _Employee;
        /// <summary>
        /// There are no comments for EventType in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<EventType> EventType
        {
            get
            {
                if ((this._EventType == null))
                {
                    this._EventType = base.CreateQuery<EventType>("[EventType]");
                }
                return this._EventType;
            }
        }
        private global::System.Data.Objects.ObjectQuery<EventType> _EventType;
        /// <summary>
        /// There are no comments for OrderState in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<OrderState> OrderState
        {
            get
            {
                if ((this._OrderState == null))
                {
                    this._OrderState = base.CreateQuery<OrderState>("[OrderState]");
                }
                return this._OrderState;
            }
        }
        private global::System.Data.Objects.ObjectQuery<OrderState> _OrderState;
        /// <summary>
        /// There are no comments for Position in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Position> Position
        {
            get
            {
                if ((this._Position == null))
                {
                    this._Position = base.CreateQuery<Position>("[Position]");
                }
                return this._Position;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Position> _Position;
        /// <summary>
        /// There are no comments for WorkOrder in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<WorkOrder> WorkOrder
        {
            get
            {
                if ((this._WorkOrder == null))
                {
                    this._WorkOrder = base.CreateQuery<WorkOrder>("[WorkOrder]");
                }
                return this._WorkOrder;
            }
        }
        private global::System.Data.Objects.ObjectQuery<WorkOrder> _WorkOrder;
        /// <summary>
        /// There are no comments for WorkOrderDetail in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<WorkOrderDetail> WorkOrderDetail
        {
            get
            {
                if ((this._WorkOrderDetail == null))
                {
                    this._WorkOrderDetail = base.CreateQuery<WorkOrderDetail>("[WorkOrderDetail]");
                }
                return this._WorkOrderDetail;
            }
        }
        private global::System.Data.Objects.ObjectQuery<WorkOrderDetail> _WorkOrderDetail;
        /// <summary>
        /// There are no comments for WorkOrderProcLog in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<WorkOrderProcLog> WorkOrderProcLog
        {
            get
            {
                if ((this._WorkOrderProcLog == null))
                {
                    this._WorkOrderProcLog = base.CreateQuery<WorkOrderProcLog>("[WorkOrderProcLog]");
                }
                return this._WorkOrderProcLog;
            }
        }
        private global::System.Data.Objects.ObjectQuery<WorkOrderProcLog> _WorkOrderProcLog;
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        public void AddToEmployee(Employee employee)
        {
            base.AddObject("Employee", employee);
        }
        /// <summary>
        /// There are no comments for EventType in the schema.
        /// </summary>
        public void AddToEventType(EventType eventType)
        {
            base.AddObject("EventType", eventType);
        }
        /// <summary>
        /// There are no comments for OrderState in the schema.
        /// </summary>
        public void AddToOrderState(OrderState orderState)
        {
            base.AddObject("OrderState", orderState);
        }
        /// <summary>
        /// There are no comments for Position in the schema.
        /// </summary>
        public void AddToPosition(Position position)
        {
            base.AddObject("Position", position);
        }
        /// <summary>
        /// There are no comments for WorkOrder in the schema.
        /// </summary>
        public void AddToWorkOrder(WorkOrder workOrder)
        {
            base.AddObject("WorkOrder", workOrder);
        }
        /// <summary>
        /// There are no comments for WorkOrderDetail in the schema.
        /// </summary>
        public void AddToWorkOrderDetail(WorkOrderDetail workOrderDetail)
        {
            base.AddObject("WorkOrderDetail", workOrderDetail);
        }
        /// <summary>
        /// There are no comments for WorkOrderProcLog in the schema.
        /// </summary>
        public void AddToWorkOrderProcLog(WorkOrderProcLog workOrderProcLog)
        {
            base.AddObject("WorkOrderProcLog", workOrderProcLog);
        }
    }
    /// <summary>
    /// There are no comments for WorkOrderModel.Employee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EmployeeID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WorkOrderModel", Name="Employee")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Employee : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="employeeID">Initial value of EmployeeID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="surname">Initial value of Surname.</param>
        public static Employee CreateEmployee(int employeeID, string name, string surname)
        {
            Employee employee = new Employee();
            employee.EmployeeID = employeeID;
            employee.Name = name;
            employee.Surname = surname;
            return employee;
        }
        /// <summary>
        /// There are no comments for Property EmployeeID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this.OnEmployeeIDChanging(value);
                this.ReportPropertyChanging("EmployeeID");
                this._EmployeeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EmployeeID");
                this.OnEmployeeIDChanged();
            }
        }
        private int _EmployeeID;
        partial void OnEmployeeIDChanging(int value);
        partial void OnEmployeeIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Surname in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this._Surname;
            }
            set
            {
                this.OnSurnameChanging(value);
                this.ReportPropertyChanging("Surname");
                this._Surname = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Surname");
                this.OnSurnameChanged();
            }
        }
        private string _Surname;
        partial void OnSurnameChanging(string value);
        partial void OnSurnameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Position in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WorkOrderModel", "FK_Employee_Position", "Position")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Position Position
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Position>("WorkOrderModel.FK_Employee_Position", "Position").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Position>("WorkOrderModel.FK_Employee_Position", "Position").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Position in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Position> PositionReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Position>("WorkOrderModel.FK_Employee_Position", "Position");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Position>("WorkOrderModel.FK_Employee_Position", "Position", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for WorkOrder in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WorkOrderModel", "FK_WorkOrder_Employee", "WorkOrder")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<WorkOrder> WorkOrder
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<WorkOrder>("WorkOrderModel.FK_WorkOrder_Employee", "WorkOrder");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<WorkOrder>("WorkOrderModel.FK_WorkOrder_Employee", "WorkOrder", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for WorkOrderModel.EventType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EventTypeId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WorkOrderModel", Name="EventType")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EventType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new EventType object.
        /// </summary>
        /// <param name="eventTypeId">Initial value of EventTypeId.</param>
        public static EventType CreateEventType(int eventTypeId)
        {
            EventType eventType = new EventType();
            eventType.EventTypeId = eventTypeId;
            return eventType;
        }
        /// <summary>
        /// There are no comments for Property EventTypeId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int EventTypeId
        {
            get
            {
                return this._EventTypeId;
            }
            set
            {
                this.OnEventTypeIdChanging(value);
                this.ReportPropertyChanging("EventTypeId");
                this._EventTypeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EventTypeId");
                this.OnEventTypeIdChanged();
            }
        }
        private int _EventTypeId;
        partial void OnEventTypeIdChanging(int value);
        partial void OnEventTypeIdChanged();
        /// <summary>
        /// There are no comments for Property EventDesc in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EventDesc
        {
            get
            {
                return this._EventDesc;
            }
            set
            {
                this.OnEventDescChanging(value);
                this.ReportPropertyChanging("EventDesc");
                this._EventDesc = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EventDesc");
                this.OnEventDescChanged();
            }
        }
        private string _EventDesc;
        partial void OnEventDescChanging(string value);
        partial void OnEventDescChanged();
        /// <summary>
        /// There are no comments for WorkOrderProcLog in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WorkOrderModel", "FK_WorkOrderProcLog_EventType", "WorkOrderProcLog")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<WorkOrderProcLog> WorkOrderProcLog
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<WorkOrderProcLog>("WorkOrderModel.FK_WorkOrderProcLog_EventType", "WorkOrderProcLog");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<WorkOrderProcLog>("WorkOrderModel.FK_WorkOrderProcLog_EventType", "WorkOrderProcLog", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for WorkOrderModel.OrderState in the schema.
    /// </summary>
    /// <KeyProperties>
    /// OrderStateId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WorkOrderModel", Name="OrderState")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class OrderState : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new OrderState object.
        /// </summary>
        /// <param name="orderStateId">Initial value of OrderStateId.</param>
        public static OrderState CreateOrderState(int orderStateId)
        {
            OrderState orderState = new OrderState();
            orderState.OrderStateId = orderStateId;
            return orderState;
        }
        /// <summary>
        /// There are no comments for Property OrderStateId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderStateId
        {
            get
            {
                return this._OrderStateId;
            }
            set
            {
                this.OnOrderStateIdChanging(value);
                this.ReportPropertyChanging("OrderStateId");
                this._OrderStateId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OrderStateId");
                this.OnOrderStateIdChanged();
            }
        }
        private int _OrderStateId;
        partial void OnOrderStateIdChanging(int value);
        partial void OnOrderStateIdChanged();
        /// <summary>
        /// There are no comments for Property StateDesc in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string StateDesc
        {
            get
            {
                return this._StateDesc;
            }
            set
            {
                this.OnStateDescChanging(value);
                this.ReportPropertyChanging("StateDesc");
                this._StateDesc = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("StateDesc");
                this.OnStateDescChanged();
            }
        }
        private string _StateDesc;
        partial void OnStateDescChanging(string value);
        partial void OnStateDescChanged();
        /// <summary>
        /// There are no comments for WorkOrder in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WorkOrderModel", "FK_WorkOrder_OrderState", "WorkOrder")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<WorkOrder> WorkOrder
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<WorkOrder>("WorkOrderModel.FK_WorkOrder_OrderState", "WorkOrder");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<WorkOrder>("WorkOrderModel.FK_WorkOrder_OrderState", "WorkOrder", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for WorkOrderModel.Position in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PositionId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WorkOrderModel", Name="Position")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Position : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Position object.
        /// </summary>
        /// <param name="positionId">Initial value of PositionId.</param>
        /// <param name="positionTitle">Initial value of PositionTitle.</param>
        public static Position CreatePosition(int positionId, string positionTitle)
        {
            Position position = new Position();
            position.PositionId = positionId;
            position.PositionTitle = positionTitle;
            return position;
        }
        /// <summary>
        /// There are no comments for Property PositionId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PositionId
        {
            get
            {
                return this._PositionId;
            }
            set
            {
                this.OnPositionIdChanging(value);
                this.ReportPropertyChanging("PositionId");
                this._PositionId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PositionId");
                this.OnPositionIdChanged();
            }
        }
        private int _PositionId;
        partial void OnPositionIdChanging(int value);
        partial void OnPositionIdChanged();
        /// <summary>
        /// There are no comments for Property PositionTitle in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionTitle
        {
            get
            {
                return this._PositionTitle;
            }
            set
            {
                this.OnPositionTitleChanging(value);
                this.ReportPropertyChanging("PositionTitle");
                this._PositionTitle = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PositionTitle");
                this.OnPositionTitleChanged();
            }
        }
        private string _PositionTitle;
        partial void OnPositionTitleChanging(string value);
        partial void OnPositionTitleChanged();
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WorkOrderModel", "FK_Employee_Position", "Employee")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Employee> Employee
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Employee>("WorkOrderModel.FK_Employee_Position", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Employee>("WorkOrderModel.FK_Employee_Position", "Employee", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for WorkOrderModel.WorkOrder in the schema.
    /// </summary>
    /// <KeyProperties>
    /// WorkOrderId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WorkOrderModel", Name="WorkOrder")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class WorkOrder : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new WorkOrder object.
        /// </summary>
        /// <param name="workOrderId">Initial value of WorkOrderId.</param>
        /// <param name="computedOrderId">Initial value of ComputedOrderId.</param>
        /// <param name="createDate">Initial value of CreateDate.</param>
        public static WorkOrder CreateWorkOrder(int workOrderId, string computedOrderId, global::System.DateTime createDate)
        {
            WorkOrder workOrder = new WorkOrder();
            workOrder.WorkOrderId = workOrderId;
            workOrder.ComputedOrderId = computedOrderId;
            workOrder.CreateDate = createDate;
            return workOrder;
        }
        /// <summary>
        /// There are no comments for Property WorkOrderId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkOrderId
        {
            get
            {
                return this._WorkOrderId;
            }
            set
            {
                this.OnWorkOrderIdChanging(value);
                this.ReportPropertyChanging("WorkOrderId");
                this._WorkOrderId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("WorkOrderId");
                this.OnWorkOrderIdChanged();
            }
        }
        private int _WorkOrderId;
        partial void OnWorkOrderIdChanging(int value);
        partial void OnWorkOrderIdChanged();
        /// <summary>
        /// There are no comments for Property ParentWorkOrderId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ParentWorkOrderId
        {
            get
            {
                return this._ParentWorkOrderId;
            }
            set
            {
                this.OnParentWorkOrderIdChanging(value);
                this.ReportPropertyChanging("ParentWorkOrderId");
                this._ParentWorkOrderId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ParentWorkOrderId");
                this.OnParentWorkOrderIdChanged();
            }
        }
        private global::System.Nullable<int> _ParentWorkOrderId;
        partial void OnParentWorkOrderIdChanging(global::System.Nullable<int> value);
        partial void OnParentWorkOrderIdChanged();
        /// <summary>
        /// There are no comments for Property ComputedOrderId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ComputedOrderId
        {
            get
            {
                return this._ComputedOrderId;
            }
            set
            {
                this.OnComputedOrderIdChanging(value);
                this.ReportPropertyChanging("ComputedOrderId");
                this._ComputedOrderId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ComputedOrderId");
                this.OnComputedOrderIdChanged();
            }
        }
        private string _ComputedOrderId;
        partial void OnComputedOrderIdChanging(string value);
        partial void OnComputedOrderIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property CreateDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this.ReportPropertyChanging("CreateDate");
                this._CreateDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreateDate");
                this.OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// There are no comments for Property CreateUser in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUser
        {
            get
            {
                return this._CreateUser;
            }
            set
            {
                this.OnCreateUserChanging(value);
                this.ReportPropertyChanging("CreateUser");
                this._CreateUser = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CreateUser");
                this.OnCreateUserChanged();
            }
        }
        private string _CreateUser;
        partial void OnCreateUserChanging(string value);
        partial void OnCreateUserChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> LastModifiedDate
        {
            get
            {
                return this._LastModifiedDate;
            }
            set
            {
                this.OnLastModifiedDateChanging(value);
                this.ReportPropertyChanging("LastModifiedDate");
                this._LastModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastModifiedDate");
                this.OnLastModifiedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _LastModifiedDate;
        partial void OnLastModifiedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLastModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedUser in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LastModifiedUser
        {
            get
            {
                return this._LastModifiedUser;
            }
            set
            {
                this.OnLastModifiedUserChanging(value);
                this.ReportPropertyChanging("LastModifiedUser");
                this._LastModifiedUser = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("LastModifiedUser");
                this.OnLastModifiedUserChanged();
            }
        }
        private string _LastModifiedUser;
        partial void OnLastModifiedUserChanging(string value);
        partial void OnLastModifiedUserChanged();
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WorkOrderModel", "FK_WorkOrder_Employee", "Employee")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Employee Employee
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Employee>("WorkOrderModel.FK_WorkOrder_Employee", "Employee").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Employee>("WorkOrderModel.FK_WorkOrder_Employee", "Employee").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Employee>("WorkOrderModel.FK_WorkOrder_Employee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Employee>("WorkOrderModel.FK_WorkOrder_Employee", "Employee", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for OrderState in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WorkOrderModel", "FK_WorkOrder_OrderState", "OrderState")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public OrderState OrderState
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OrderState>("WorkOrderModel.FK_WorkOrder_OrderState", "OrderState").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OrderState>("WorkOrderModel.FK_WorkOrder_OrderState", "OrderState").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for OrderState in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<OrderState> OrderStateReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OrderState>("WorkOrderModel.FK_WorkOrder_OrderState", "OrderState");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<OrderState>("WorkOrderModel.FK_WorkOrder_OrderState", "OrderState", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for WorkOrderDetail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WorkOrderModel", "FK_WorkOrderDetail_WorkOrder", "WorkOrderDetail")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<WorkOrderDetail> WorkOrderDetail
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<WorkOrderDetail>("WorkOrderModel.FK_WorkOrderDetail_WorkOrder", "WorkOrderDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<WorkOrderDetail>("WorkOrderModel.FK_WorkOrderDetail_WorkOrder", "WorkOrderDetail", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for WorkOrderProcLog in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WorkOrderModel", "FK_WorkOrderProcLog_WorkOrder", "WorkOrderProcLog")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<WorkOrderProcLog> WorkOrderProcLog
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<WorkOrderProcLog>("WorkOrderModel.FK_WorkOrderProcLog_WorkOrder", "WorkOrderProcLog");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<WorkOrderProcLog>("WorkOrderModel.FK_WorkOrderProcLog_WorkOrder", "WorkOrderProcLog", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for WorkOrderModel.WorkOrderDetail in the schema.
    /// </summary>
    /// <KeyProperties>
    /// WorkFlowDetailId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WorkOrderModel", Name="WorkOrderDetail")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class WorkOrderDetail : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new WorkOrderDetail object.
        /// </summary>
        /// <param name="workFlowDetailId">Initial value of WorkFlowDetailId.</param>
        /// <param name="priorityId">Initial value of PriorityId.</param>
        public static WorkOrderDetail CreateWorkOrderDetail(int workFlowDetailId, int priorityId)
        {
            WorkOrderDetail workOrderDetail = new WorkOrderDetail();
            workOrderDetail.WorkFlowDetailId = workFlowDetailId;
            workOrderDetail.PriorityId = priorityId;
            return workOrderDetail;
        }
        /// <summary>
        /// There are no comments for Property WorkFlowDetailId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkFlowDetailId
        {
            get
            {
                return this._WorkFlowDetailId;
            }
            set
            {
                this.OnWorkFlowDetailIdChanging(value);
                this.ReportPropertyChanging("WorkFlowDetailId");
                this._WorkFlowDetailId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("WorkFlowDetailId");
                this.OnWorkFlowDetailIdChanged();
            }
        }
        private int _WorkFlowDetailId;
        partial void OnWorkFlowDetailIdChanging(int value);
        partial void OnWorkFlowDetailIdChanged();
        /// <summary>
        /// There are no comments for Property PriorityId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PriorityId
        {
            get
            {
                return this._PriorityId;
            }
            set
            {
                this.OnPriorityIdChanging(value);
                this.ReportPropertyChanging("PriorityId");
                this._PriorityId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PriorityId");
                this.OnPriorityIdChanged();
            }
        }
        private int _PriorityId;
        partial void OnPriorityIdChanging(int value);
        partial void OnPriorityIdChanged();
        /// <summary>
        /// There are no comments for Property EstimatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> EstimatedDate
        {
            get
            {
                return this._EstimatedDate;
            }
            set
            {
                this.OnEstimatedDateChanging(value);
                this.ReportPropertyChanging("EstimatedDate");
                this._EstimatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EstimatedDate");
                this.OnEstimatedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _EstimatedDate;
        partial void OnEstimatedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnEstimatedDateChanged();
        /// <summary>
        /// There are no comments for Property OrderEndTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> OrderEndTime
        {
            get
            {
                return this._OrderEndTime;
            }
            set
            {
                this.OnOrderEndTimeChanging(value);
                this.ReportPropertyChanging("OrderEndTime");
                this._OrderEndTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OrderEndTime");
                this.OnOrderEndTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _OrderEndTime;
        partial void OnOrderEndTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnOrderEndTimeChanged();
        /// <summary>
        /// There are no comments for WorkOrder in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WorkOrderModel", "FK_WorkOrderDetail_WorkOrder", "WorkOrder")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public WorkOrder WorkOrder
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<WorkOrder>("WorkOrderModel.FK_WorkOrderDetail_WorkOrder", "WorkOrder").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<WorkOrder>("WorkOrderModel.FK_WorkOrderDetail_WorkOrder", "WorkOrder").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for WorkOrder in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<WorkOrder> WorkOrderReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<WorkOrder>("WorkOrderModel.FK_WorkOrderDetail_WorkOrder", "WorkOrder");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<WorkOrder>("WorkOrderModel.FK_WorkOrderDetail_WorkOrder", "WorkOrder", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for WorkOrderModel.WorkOrderProcLog in the schema.
    /// </summary>
    /// <KeyProperties>
    /// WorkOrderProcLogId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="WorkOrderModel", Name="WorkOrderProcLog")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class WorkOrderProcLog : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new WorkOrderProcLog object.
        /// </summary>
        /// <param name="workOrderProcLogId">Initial value of WorkOrderProcLogId.</param>
        /// <param name="computedEventDesc">Initial value of ComputedEventDesc.</param>
        /// <param name="createUser">Initial value of CreateUser.</param>
        /// <param name="createDate">Initial value of CreateDate.</param>
        public static WorkOrderProcLog CreateWorkOrderProcLog(int workOrderProcLogId, string computedEventDesc, string createUser, global::System.DateTime createDate)
        {
            WorkOrderProcLog workOrderProcLog = new WorkOrderProcLog();
            workOrderProcLog.WorkOrderProcLogId = workOrderProcLogId;
            workOrderProcLog.ComputedEventDesc = computedEventDesc;
            workOrderProcLog.CreateUser = createUser;
            workOrderProcLog.CreateDate = createDate;
            return workOrderProcLog;
        }
        /// <summary>
        /// There are no comments for Property WorkOrderProcLogId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkOrderProcLogId
        {
            get
            {
                return this._WorkOrderProcLogId;
            }
            set
            {
                this.OnWorkOrderProcLogIdChanging(value);
                this.ReportPropertyChanging("WorkOrderProcLogId");
                this._WorkOrderProcLogId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("WorkOrderProcLogId");
                this.OnWorkOrderProcLogIdChanged();
            }
        }
        private int _WorkOrderProcLogId;
        partial void OnWorkOrderProcLogIdChanging(int value);
        partial void OnWorkOrderProcLogIdChanged();
        /// <summary>
        /// There are no comments for Property ComputedEventDesc in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ComputedEventDesc
        {
            get
            {
                return this._ComputedEventDesc;
            }
            set
            {
                this.OnComputedEventDescChanging(value);
                this.ReportPropertyChanging("ComputedEventDesc");
                this._ComputedEventDesc = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ComputedEventDesc");
                this.OnComputedEventDescChanged();
            }
        }
        private string _ComputedEventDesc;
        partial void OnComputedEventDescChanging(string value);
        partial void OnComputedEventDescChanged();
        /// <summary>
        /// There are no comments for Property CreateUser in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUser
        {
            get
            {
                return this._CreateUser;
            }
            set
            {
                this.OnCreateUserChanging(value);
                this.ReportPropertyChanging("CreateUser");
                this._CreateUser = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreateUser");
                this.OnCreateUserChanged();
            }
        }
        private string _CreateUser;
        partial void OnCreateUserChanging(string value);
        partial void OnCreateUserChanged();
        /// <summary>
        /// There are no comments for Property CreateDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this.ReportPropertyChanging("CreateDate");
                this._CreateDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreateDate");
                this.OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// There are no comments for EventType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WorkOrderModel", "FK_WorkOrderProcLog_EventType", "EventType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public EventType EventType
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EventType>("WorkOrderModel.FK_WorkOrderProcLog_EventType", "EventType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EventType>("WorkOrderModel.FK_WorkOrderProcLog_EventType", "EventType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for EventType in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<EventType> EventTypeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<EventType>("WorkOrderModel.FK_WorkOrderProcLog_EventType", "EventType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<EventType>("WorkOrderModel.FK_WorkOrderProcLog_EventType", "EventType", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for WorkOrder in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("WorkOrderModel", "FK_WorkOrderProcLog_WorkOrder", "WorkOrder")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public WorkOrder WorkOrder
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<WorkOrder>("WorkOrderModel.FK_WorkOrderProcLog_WorkOrder", "WorkOrder").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<WorkOrder>("WorkOrderModel.FK_WorkOrderProcLog_WorkOrder", "WorkOrder").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for WorkOrder in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<WorkOrder> WorkOrderReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<WorkOrder>("WorkOrderModel.FK_WorkOrderProcLog_WorkOrder", "WorkOrder");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<WorkOrder>("WorkOrderModel.FK_WorkOrderProcLog_WorkOrder", "WorkOrder", value);
                }
            }
        }
    }
}
